### PR TITLE
Add Update Check to the package index

### PR DESCRIPTION
**Pull request by stevegrunwell**
Adds [the `wp update-check` package](https://github.com/growella/update-check), to automatically check for available core, plugin, or theme updates.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
FYI - accepting new package submissions is on hold: https://github.com/wp-cli/package-index/pull/90#issuecomment-264880112

**Comment by stevegrunwell** [comment]
Roger that, thanks for the heads up!

**Comment by danielbachhuber** [comment]
@stevegrunwell We're now discussing what to do with the package index if you'd like to weigh in on this post: https://make.wordpress.org/cli/2017/07/05/how-should-we-embark-upon-new-feature-development/

**Comment by danielbachhuber** [comment]
We've decided to [deprecate the Package Index](https://make.wordpress.org/cli/2017/07/18/feature-development-discussion-recap/).

If there are any commands you'd like to suggest official implementations for, the ideas repo is a good place for that: https://github.com/wp-cli/ideas

**Comment by stevegrunwell** [comment]
Thanks for the follow-up; I just revisited the original discussion thread and found that my comment (short version: "C") was in localStorage but had never been submitted 🤦‍♂️

**Comment by danielbachhuber** [comment]
👌

**Pull request closed without merging**
