### PR TITLE
Add Gravity Forms CLI

### PR DESCRIPTION
**Pull request by stevehenty**
A set of WP-CLI commands to manage Gravity Forms.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
FYI - accepting new package submissions is on hold: https://github.com/wp-cli/package-index/pull/90#issuecomment-264880112

Generally, my recommendation is that WP-CLI commands specific to WordPress plugins should be bundled directly in the plugin.

**Comment by stevehenty** [comment]
Thanks for letting me know. i'll keep an eye out for developments.

We separated it for a couple of reasons. We wanted sysadmins and hosts to be able to download it separately (e.g. to verify checksums on older versions). Also, it can be used to download and install the latest version of Gravity Forms.

Here's the plugin:
https://wordpress.org/plugins/gravityformscli/

**Comment by danielbachhuber** [comment]
@stevehenty We're now discussing what to do with the package index if you'd like to weigh in on this post: https://make.wordpress.org/cli/2017/07/05/how-should-we-embark-upon-new-feature-development/

**Comment by danielbachhuber** [comment]
We've decided to [deprecate the Package Index](https://make.wordpress.org/cli/2017/07/18/feature-development-discussion-recap/).

If there are any commands you'd like to suggest official implementations for, the ideas repo is a good place for that: https://github.com/wp-cli/ideas

**Pull request closed without merging**
