### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by nerrad**
Adds wp-cli package for the Event Espresso plugin.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
FYI - accepting new package submissions is on hold: https://github.com/wp-cli/package-index/pull/90#issuecomment-264880112

**Comment by danielbachhuber** [comment]
@nerrad We're now discussing what to do with the package index if you'd like to weigh in on this post: https://make.wordpress.org/cli/2017/07/05/how-should-we-embark-upon-new-feature-development/

**Comment by nerrad** [comment]
hey thanks for letting me know.  Added my feedback there.  I'm on vacay at the moment so there could be delays to any further responses there.

**Comment by danielbachhuber** [comment]
We've decided to [deprecate the Package Index](https://make.wordpress.org/cli/2017/07/18/feature-development-discussion-recap/).

If there are any commands you'd like to suggest official implementations for, the ideas repo is a good place for that: https://github.com/wp-cli/ideas

**Pull request closed without merging**
