### PR TITLE
Add my wp-cli-salts-generator

### PR DESCRIPTION
**Pull request by feryardiant**
Hi there,

Just create my first wp-cli package for generating salts keys. This package actualy has same functionality as [`sebastiaandegeus/wp-cli-salts-command`](https://github.com/sebastiaandegeus/wp-cli-salts-command) but with capability to generate localy (offline).

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@feryardiant Could you consider contributing your improvements to the existing package?

**Comment by feryardiant** [comment]
Hi @danielbachhuber,

Sure if I could, that's actually my initial though but when I've seen [an issue](https://github.com/sebastiaandegeus/wp-cli-salts-command/pull/3) from 2015 without any response from the author, I suddenly change my mind.

cc: @sebastiaandegeus

**Comment by sebastiaandegeus** [comment]
That reported issue kind of disappeared from my radar. If your still interested you can make a pull request and I will take a look at it.

**Comment by danielbachhuber** [comment]
@feryardiant @sebastiaandegeus Thanks for engaging in this conversation folks.

I'm trying to do something a little bit different than the WordPress Plugin Directory in that I'd much prefer there be one implementation of a particular WP-CLI command that multiple developers help maintain, instead of multiple implementations of a particular WP-CLI command that each only have a single maintainer. Does this distinction make sense?

While I agree it can be a bit more difficult to collaborate with someone than do something on your own, I think there's a two-fold benefit in taking this approach:

* You (as a WP-CLI package author) will feel less burdened in maintaining your package, because you have a partner to help you out.
* You (as a WP-CLI user) will have greater confidence in using the packages in the package index because you know there's a small community of maintainers around each of them.

What questions or feedback do you have on this vision? What do you think I can do to better help make this a reality?

cc @wp-cli/package-authors 

See https://github.com/wp-cli/wp-cli/issues/3197 for some prior conversation.

**Comment by szepeviktor** [comment]
Safe salts: https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/wp-safe-salt.php

**Comment by szepeviktor** [comment]
+1 for audited plugins, one/task

**Comment by feryardiant** [comment]
Hi @sebastiaandegeus, thanks for your response.

> If your still interested you can make a pull request and I will take a look at it.

Of course, but before that I have a quick question for you. Would you like to have supports for generating to `wp-config.php` or `.env` file automaticaly?

AFAIK, you package could only generate to plain `php` file, right? In my package, I've planned to add capability below. (_but have no time yet_)

- Generate to one of certain file:
  - `.env`, for them who were using [bedrock](https://roots.io/bedrock/) for their project
  - `wp-config.php`, for them who were using native wordpress directory structure
- Will check `.env` file in root project, if exists the generated salts will replacing `generateme` text in [`.env`](https://github.com/roots/bedrock/blob/master/.env.example) file,
- If `.env` is not exists, it will check `wp-config.php` file in root project, if exists the generated salts will replacing `put your unique phrase here` text in [`wp-config`](https://github.com/WordPress/WordPress/blob/master/wp-config-sample.php#L49-L56) file.
- If none of both are exists, simply print out the generated salts to the terminal.

I've also considering some situations that might occurred according feature above but now let me know your thought first. 😝

Best regards.

**Comment by danielbachhuber** [comment]
@sebastiaandegeus Would you be up for adding @feryardiant as a contributor on your project? Or, would you prefer I remove your project from the Package Index in favor of @feryardiant's ?

**Comment by sebastiaandegeus** [comment]
Right now both packages do basically the same. I have some pull requests open concerning output formats that I will implement but I don't want to make this package too complicated. I think my package should handle the basic salts api and output in a couple different format and that's it. If people have very exotic ways of including salts they may implement their own commands for doing so. 

Also I'm not really convinced in implementing the generation of salts outside of the official salts api. Using user land functions to generate random data can be dangerous in the long run.

**Comment by sebastiaandegeus** [comment]
Apart from that I'm open to make this package a joint effort.

**Comment by feryardiant** [comment]
> but I don't want to make this package too complicated. I think my package should handle the basic salts api and output in a couple different format and that's it.

So, you should check my package @sebastiaandegeus, I've already implementing multi-format options.

```shell
# default is table
wp salts-gen --format=[table|csv|ids|json|yaml]
```

Also, capability to generate salts offline using built-in wordpress [`wp_generate_password()`](https://github.com/feryardiant/wp-cli-salts-generator/blob/master/command.php#L46) function instead using [wp-api](https://api.wordpress.org/secret-key/1.1/salt/), the reason is because wp actually using [same function](https://github.com/WordPress/WordPress/blob/master/wp-includes/pluggable.php#L1986) to generate salts when using web ui installer. But we also have option to get salt from the [API](https://github.com/feryardiant/wp-cli-salts-generator/blob/master/command.php#L29-L30), simply by running.

```shell
wp salts-gen --wp-api
```

any thoughts?

**Comment by sebastiaandegeus** [comment]
By going for generate_password right away you skipped the most secure way of generating the salts. See `wordpress/wp-admin/setup-config.php`. Preferably we use that most secure way with `CSPRNG` `random_int()`. But I think we should move the discussion about specifics somewhere else. 

I made issues in my repo to further discuss them and add pull requests when we implement them.
https://github.com/sebastiaandegeus/wp-cli-salts-command/issues

**Comment by danielbachhuber** [comment]
@feryardiant @sebastiaandegeus Another possibility is that we transfer one of your commands to the WP-CLI organization, and it becomes an official project of WP-CLI.

**Comment by feryardiant** [comment]
@sebastiaandegeus yes you're right. I'll make PR this weekend.

**Comment by danielbachhuber** [comment]
@feryardiant @sebastiaandegeus Just wanted to follow up on this to report that I'm going to refrain from accepting new packages indefinitely. I want to have a clearer sense of how a curated directory is going to work out before I accept more packages, and want to spend more time thinking about how to proceed before I make any decisions.

**Comment by danielbachhuber** [comment]
@feryardiant @sebastiaandegeus We're now discussing what to do with the package index if you'd like to weigh in on this post: https://make.wordpress.org/cli/2017/07/05/how-should-we-embark-upon-new-feature-development/

**Comment by danielbachhuber** [comment]
We've decided to [deprecate the Package Index](https://make.wordpress.org/cli/2017/07/18/feature-development-discussion-recap/).

If there are any commands you'd like to suggest official implementations for, the ideas repo is a good place for that: https://github.com/wp-cli/ideas

**Pull request closed without merging**
