### PR TITLE
Added diggy/polylang-cli

### PR DESCRIPTION
**Pull request by szepeviktor**
@danielbachhuber Please merge this one.
Thanks.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Duplicate of #93

**Comment by danielbachhuber** [comment]
FYI - accepting new package submissions is on hold: https://github.com/wp-cli/package-index/pull/90#issuecomment-264880112

**Comment by danielbachhuber** [comment]
@szepeviktor We're now discussing what to do with the package index if you'd like to weigh in on this post: https://make.wordpress.org/cli/2017/07/05/how-should-we-embark-upon-new-feature-development/

**Comment by danielbachhuber** [comment]
We've decided to [deprecate the Package Index](https://make.wordpress.org/cli/2017/07/18/feature-development-discussion-recap/).

It looks like the installation instructions for the package are already correct.

If there are any commands you'd like to suggest official implementations off, the ideas repo is a good place for that: https://github.com/wp-cli/ideas

**Pull request closed without merging**
