### PR TITLE
Add wp-cli-fixtures

### PR DESCRIPTION
**Pull request by nlemoine**
Easily generate fake content for WordPress.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Thanks for the submission, @nlemoine !

Could you explain how this package is different than https://github.com/trendwerk/faker ?

**Comment by nlemoine** [comment]
See https://github.com/trendwerk/faker/pull/8

**Comment by danielbachhuber** [comment]
Ok. My preference is for canonical implementations, instead of having multiple packages implementing similar features.

See conversation in https://github.com/wp-cli/package-index/pull/90#issuecomment-258513610 for some of the back story.

Thoughts?

**Comment by nlemoine** [comment]
I have some mixed feelings about it. 

I totally understand your arguments, it makes sense that you don't want to end up like WordPress plugins repo, with thousands of plugins providing the same feature or unmaintained repos. 

On the other hand, the diversity of implementations, designs is what makes some repository great and provides various choices to developers. I believe wp cli packages are a bit different from WordPress plugins:
- they mostly target WordPress developers, not end WordPress users which are not the same kind of audience at all
- It's harder to make profits with a wp cli package, they are probably a less profitable business than freemium WordPress plugins (due to audience size). There's no interest for companies/developers/agencies to write some freemium packages. I think you won't face the five-packages-for-the-same-feature issue here. 

You can check my link here: https://github.com/wp-cli/package-index/pull/95#issuecomment-262834007 We may collaborate but may also disagree and keep our packages separated. It's ok if my version doesn't end up in the package index. I wrote it in the first place for own needs.

**Comment by danielbachhuber** [comment]
> I totally understand your arguments, it makes sense that you don't want to end up like WordPress plugins repo, with thousands of plugins providing the same feature or unmaintained repos.
> 
> On the other hand, the diversity of implementations, designs is what makes some repository great and provides various choices to developers.

How do you think we could achieve both of these goals?

**Comment by nlemoine** [comment]
They are contradictory. I can't tell, I was just giving my thoughts on your comment 😉

**Comment by danielbachhuber** [comment]
Understandable.

More than happy to take any suggestions you might have to help get to the end state I'm describing.

**Comment by danielbachhuber** [comment]
@nlemoine Just wanted to follow up on this to report that I'm going to refrain from accepting new packages indefinitely. I want to have a clearer sense of how a curated directory is going to work out before I accept more packages, and want to spend more time thinking about how to proceed before I make any decisions.

**Comment by nlemoine** [comment]
No problem.

**Comment by danielbachhuber** [comment]
@nlemoine We're now discussing what to do with the package index if you'd like to weigh in on this post: https://make.wordpress.org/cli/2017/07/05/how-should-we-embark-upon-new-feature-development/

**Comment by danielbachhuber** [comment]
We've decided to [deprecate the Package Index](https://make.wordpress.org/cli/2017/07/18/feature-development-discussion-recap/).

If there are any commands you'd like to suggest official implementations for, the ideas repo is a good place for that: https://github.com/wp-cli/ideas

**Pull request closed without merging**
