### PR TITLE
Add 10up/wp-vulnerability-scanner

### PR DESCRIPTION
**Pull request by Ritesh-patel**

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Thanks @Ritesh-patel !

How is this command different than https://github.com/markri/wp-sec ?

**Comment by TheLastCicada** [comment]
It is admittedly very similar and pretty much accomplishes the same thing.  We were working on this vulnerability scanner and had pretty much finished it when wp-sec made it in the package index.  So now we have this vulnerability tool that is built and could be seen as redundant with wp-sec, which is already in the package index.  This brings up the question..... should the package index only have 1 tool to solve each problem?  We are submitting this to the package index because 1.) we think it is useful 2.) the package index makes it easy for us to install it and 3.) we know we are going to maintain it going forward.  

I'm going to reach out to the author of wp-sec to discuss his plans for the tool.  Let me know what you think about the package index and if it is curated to avoid duplicate functionality or what the ultimate strategy will be with that.

**Comment by danielbachhuber** [comment]
> Let me know what you think about the package index and if it is curated to avoid duplicate functionality or what the ultimate strategy will be with that.

Still a work in progress, but see https://github.com/wp-cli/package-index/pull/90 and https://github.com/wp-cli/package-index/pull/95 for some past discussion. My preference is for canonical packages, although it's obvious we have some work to do on the community management aspect.

**Comment by TheLastCicada** [comment]
Thanks - I think that approach makes sense, though will take constant curation.  I'm opening the discussion with the author of wp-sec right now and we'll see where that goes.

**Comment by danielbachhuber** [comment]
> Thanks - I think that approach makes sense, though will take constant curation.

Yep. We're definitely at the "Here's the goal, how do we get there?" stage.

> I'm opening the discussion with the author of wp-sec right now and we'll see where that goes.

Sounds good. Feel free to loop me in as needed.

**Comment by danielbachhuber** [comment]
@TheLastCicada @Ritesh-patel Just wanted to follow up on this to report that I'm going to refrain from accepting new packages indefinitely. I want to have a clearer sense of how a curated directory is going to work out before I accept more packages, and want to spend more time thinking about how to proceed before I make any decisions.

**Comment by danielbachhuber** [comment]
@Ritesh-patel @TheLastCicada We're now discussing what to do with the package index if you'd like to weigh in on this post: https://make.wordpress.org/cli/2017/07/05/how-should-we-embark-upon-new-feature-development/

**Comment by danielbachhuber** [comment]
We've decided to [deprecate the Package Index](https://make.wordpress.org/cli/2017/07/18/feature-development-discussion-recap/).

If there are any commands you'd like to suggest official implementations for, the ideas repo is a good place for that: https://github.com/wp-cli/ideas

**Pull request closed without merging**
